openapi: 3.0.3
info:
  title: API Test
  description: >
    This is a example test
  version: 1.0.0
host: "localhost:3000"
schemes:
  - "http"
tags:
  - name: user
    description: Operations about user
paths:
  /users:
    get:
      tags:
        - user
      summary: Get a list of users
      description: Get a list with all registed users
      operationId: getListOfUsers
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'          
  /user:
    post:
      tags:
        - user
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /user/{userName}:
    get:
      tags:
        - user
      summary: Get an user by name
      description: Returns a single user
      operationId: getUserByName
      parameters:
        - name: userName
          in: path
          description: Name of the user to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
    put:
      tags:
        - user
      summary: Update an user by name
      description: Returns a message with the result
      operationId: updateUserByName
      parameters:
        - name: userName
          in: path
          description: Name of the user to return
          required: true
          schema:
            type: string
      requestBody:
        description: New user information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
    patch:
      tags:
        - user
      summary: Partial update an user by name
      description: Returns a message with the result
      operationId: partialUpdateUserByName
      parameters:
        - name: userName
          in: path
          description: Name of the user to return
          required: true
          schema:
            type: string
      requestBody:
        description: New user information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
    delete:
      tags:
        - user
      summary: Deletes an user
      description: delete an user
      operationId: deleteUser
      parameters:
        - name: userName
          in: path
          description: 'Name of the user to delete'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: ´#/components/schemas/User´
        '404':
          description: Invalid user's name
components:
  schemas:
    User:
      type: object
      properties:
        nome:
          type: string
          example: theUser
        email:
          type: string
          example: john@email.com
        idade:
          type: integer
          example: '34'
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/User'